//
//  Cat.swift
//  PetLog
//
//  Created by Hao Qin on 5/6/21.
//

import Foundation

struct Cat {
	let allBreeds = [
		"Abyssinian",
		"Aegean",
		"American Bobtail",
		"American Curl",
		"American Polydactyl",
		"American Shorthair",
		"American Wirehair",
		"Arabian Mau",
		"Asian",
		"Asian Semi-longhair",
		"Australian Mist",
		"Balinese",
		"Bambino",
		"Bengal",
		"Birman",
		"Bombay",
		"Brazilian Shorthair",
		"British Longhair",
		"British Shorthair",
		"Burmese",
		"Burmilla",
		"California Spangled",
		"Chantilly/Tiffany",
		"Chartreux",
		"Chausie",
		"Cheetoh",
		"Colorpoint Shorthair",
		"Cornish Rex",
		"Cymric",
		"Cyprus",
		"Devon Rex",
		"Donskoy/Don Sphynx",
		"Dragon Li",
		"Dwelf",
		"Egyptian Mau",
		"European Shorthair",
		"Exotic Shorthair",
		"German Rex",
		"Havana Brown",
		"Highlander",
		"Himalayan / Colorpoint Persian",
		"Japanese Bobtail",
		"Javanese",
		"Khao Manee",
		"Korat",
		"Kurilian Bobtail",
		"LaPerm",
		"Maine Coon",
		"Manx",
		"Mekong Bobtail",
		"Minskin",
		"Munchkin",
		"Napoleon",
		"Nebelung",
		"Norwegian Forest",
		"Ocicat",
		"Ojos Azules",
		"Oregon Rex",
		"Oriental Bicolor",
		"Oriental Longhair",
		"Oriental Shorthair",
		"Persian",
		"Peterbald",
		"Pixie-bob",
		"Ragamuffin",
		"Ragdoll",
		"Russian Black, White or Tabby",
		"Russian Blue",
		"Savannah",
		"Scottish Fold",
		"Selkirk Rex",
		"Serengeti",
		"Siamese",
		"Siberian",
		"Singapura",
		"Snowshoe",
		"Sokoke",
		"Somali",
		"Sphynx",
		"Thai",
		"Tonkinese",
		"Toyger",
		"Turkish Angora",
		"Turkish Van",
		"Ukrainian Levkoy",
		"York Chocolate"
	]
}
