//
//  Dog.swift
//  PetLog
//
//  Created by Hao Qin on 5/5/21.
//

import Foundation

struct Dog {
	let allBreeds = [
		"Affenpinscher",
		"Afghan Hound",
		"Airedale Terrier",
		"Akita",
		"Alaskan Malamute",
		"American Hairless Terrier",
		"American Staffordshire Terrier",
		"Anatolian Shepherd Dog",
		"Australian Cattle Dog",
		"Australian Kelpie",
		"Australian Silky Terrier",
		"Australian Stumpy Tail Cattle Dog",
		"Australian Terrier",
		"Azawakh",
		"Basenji",
		"Basset Fauve de Bretagne",
		"Basset Hound",
		"Beagle",
		"Bearded Collie",
		"Bedlington Terrier",
		"Belgian Shepherd Dog",
		"Belgian Shepherd Dog (Groenendael)",
		"Belgian Shepherd Dog (Laekenois)",
		"Belgian Shepherd Dog (Malinois)",
		"Belgian Shepherd Dog (Tervueren)",
		"Bergamasco Shepherd Dog",
		"Bernese Mountain Dog",
		"Bichon Frise",
		"Black and Tan Coonhound",
		"Bloodhound",
		"Bluetick Coonhound",
		"Border Collie",
		"Border Terrier",
		"Borzoi",
		"Boston Terrier",
		"Bouvier des Flandres",
		"Boxer",
		"Bracco Italiano",
		"Briard",
		"British Bulldog",
		"Brittany",
		"Bull Terrier",
		"Bull Terrier (Miniature)",
		"Bullmastiff",
		"Cairn Terrier",
		"Canaan Dog",
		"Canadian Eskimo Dog",
		"Cane Corso",
		"Caucasian Shepherd Dog",
		"Cavoodle",
		"Central Asian Shepherd Dog",
		"Cesky Terrier",
		"Chesapeake Bay Retriever",
		"Chihuahua",
		"Chinese Crested Dog",
		"Chow Chow",
		"Clumber Spaniel",
		"Cockapoo",
		"Cocker Spaniel",
		"Coton De Tulear",
		"Curly Coated Retriever",
		"Dachshund",
		"Dalmatian",
		"Dandie Dinmont Terrier",
		"Deerhound",
		"Dobermann",
		"Dogue de Bordeaux",
		"Dutch Shepherd Dog",
		"English Setter",
		"English Springer Spaniel",
		"English Toy Terrier (Black and Tan)",
		"Estrela Mountain Dog",
		"Eurasier",
		"Field Spaniel",
		"Finnish Lapphund",
		"Finnish Spitz",
		"Flat Coated Retriever",
		"Fox Terrier",
		"Foxhound",
		"French Bulldog",
		"German Hunting Terrier",
		"German Pinscher",
		"German Shepherd Dog",
		"German Shorthaired Pointer",
		"German Spitz",
		"German Wirehaired Pointer",
		"Glen of Imaal Terrier",
		"Golden Retriever",
		"Gordon Setter",
		"Grand Basset Griffon Vendeen",
		"Great Dane",
		"Greyhound",
		"Griffon Bruxellois",
		"Groodle",
		"Hamiltonstovare",
		"Harrier",
		"Havanese",
		"Hungarian Vizsla",
		"Ibizan Hound",
		"Icelandic Sheepdog",
		"Irish Red and White Setter",
		"Irish Setter",
		"Irish Terrier",
		"Irish Water Spaniel",
		"Irish Wolfhound",
		"Italian Greyhound",
		"Italian Spinone",
		"Jack Russell Terrier",
		"Japanese Chin",
		"Japanese Spitz",
		"Kangal Shepherd Dog",
		"Keeshond",
		"Kerry Blue Terrier",
		"King Charles Spaniel",
		"Komondor",
		"Kuvasz",
		"Labradoodle",
		"Labrador Retriever",
		"Lagotto Romagnolo",
		"Lakeland Terrier",
		"Landseer (European Continental Type)",
		"Large Munsterlander",
		"Leonberger",
		"Lhasa Apso",
		"Lowchen",
		"Maltese",
		"Maltipoo",
		"Manchester Terrier",
		"Maremma Sheepdog",
		"Mastiff",
		"Neapolitan Mastiff",
		"Newfoundland",
		"Norfolk Terrier",
		"Norwegian Buhund",
		"Norwegian Elkhound",
		"Norwich Terrier",
		"Nova Scotia Duck Tolling Retriever",
		"Old English Sheepdog",
		"Otterhound",
		"Papillon",
		"Parson Russell Terrier",
		"Pekingese",
		"Peruvian Hairless Dog",
		"Petit Basset Griffon Vendeen",
		"Pharaoh Hound",
		"Pinscher",
		"Pointer",
		"Polish Lowland Sheepdog",
		"Pomeranian",
		"Poodle",
		"Portuguese Podengo",
		"Portuguese Water Dog",
		"Pug",
		"Puli",
		"Pumi",
		"Pyrenean Mastiff",
		"Pyrenean Mountain Dog",
		"Rhodesian Ridgeback",
		"Rottweiler",
		"Russian Black Terrier",
		"Russian Toy",
		"Saluki",
		"Samoyed",
		"Schipperke",
		"Schnoodle",
		"Scottish Terrier",
		"Sealyham Terrier",
		"Shar Pei",
		"Shetland Sheepdog",
		"Shiba Inu",
		"Shih Tzu",
		"Shih-Poo",
		"Siberian Husky",
		"Skye Terrier",
		"Sloughi",
		"Soft Coated Wheaten Terrier",
		"Spanish Mastiff",
		"Spanish Water Dog",
		"Spoodle",
		"St Bernard",
		"Staffordshire Bull Terrier",
		"Schnauzer",
		"Sussex Spaniel",
		"Swedish Lapphund",
		"Swedish Vallhund",
		"Tatra Shepherd Dog",
		"Tenterfield Terrier",
		"Tibetan Mastiff",
		"Tibetan Spaniel",
		"Tibetan Terrier",
		"Weimaraner",
		"Welsh Corgi",
		"Welsh Springer Spaniel",
		"Welsh Terrier",
		"West Highland White Terrier",
		"Whippet",
		"White Swiss Shepherd Dog",
		"Wirehaired Slovakian Pointer",
		"Xoloitzcuintle",
		"Yorkshire Terrier",
		"Zuchon"
	]
}
